.test_setup:
  stage: test
#  except:
#    - schedules
#    - master
#    - wse-master
#    - salmon-accordion
  only:
    - external_pull_requests
    - merge_requests
    - web
  retry:
    max: 2
    when: runner_system_failure
  interruptible: true

frontend:
  extends: .test_setup
  script:
    - echo ""

minitest:
  extends: .test_setup
  script:
    - echo ""

rspec:
  extends: .test_setup
  parallel: 10
  script:
    - echo ""
